name: create&release  
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run:  |
          echo "DATE=$(date +'%y%m%d%H')" >> $GITHUB_ENV
      - name: Checkout
        uses: symbuzzer/fork-checkout-repo@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Creating module zip
        run:  |
          mkdir -p zip
          find . -type d -exec sh -c 'zip -r "{}.zip" "{}"' \;
          mv *.zip zip/
      - name: Create and upload release asset
        uses: symbuzzer/fork-github-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.DATE }}
          name: Update date = ${{ env.DATE }}
          body: Please check [changelog](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for changes
          files: zip/*
          gzip: false
          draft: false
          prerelease: false
          allow_override: true
      - name: Cleanup modules zip files
        run:  |
          rm -rf zip
